<?php

namespace AppBundle\Repository;

/**
 * AbonnerReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonnerReponseRepository extends \Doctrine\ORM\EntityRepository
{
}
