<?php

namespace AppBundle\Repository;

/**
 * AbonnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonnerRepository extends \Doctrine\ORM\EntityRepository
{
}
