# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\Abonner: bcrypt
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ["ROLE_ADMIN","ROLE_USER"]
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        orm:
            entity:
                class: AppBundle\Entity\Abonner

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            #            provider: app_user_provider
            form_login:
                login_path: login
                check_path: loginCheck
                always_use_default_target_path: true
                default_target_path: /redirect-login
                use_referer: true
            logout: true
            anonymous: true
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/questionnaire, role: ROLE_USER }
