<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRrvz33s\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRrvz33s/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRrvz33s.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRrvz33s\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRrvz33s\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Rrvz33s',
    'container.build_id' => '15abd631',
    'container.build_time' => 1543655266,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerRrvz33s');
