<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLfa2qek\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLfa2qek/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLfa2qek.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLfa2qek\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerLfa2qek\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Lfa2qek',
    'container.build_id' => '86c86cb7',
    'container.build_time' => 1543677671,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerLfa2qek');
